export const GET_FASHION_DATA_REQUEST = "GET_FASHION_DATA_REQUEST";
export const GET_FASHION_DATA_SUCCESS = "GET_FASHION_DATA_SUCCESS";
export const GET_FASHION_DATA_FAILURE = "GET_FASHION_DATA_FAILURE";