export const GET_GROCERIES_DATA_REQUEST = "GET_GROCERIES_DATA_REQUEST";
export const GET_GROCERIES_DATA_SUCCESS = "GET_GROCERIES_DATA_SUCCESS";
export const GET_GROCERIES_DATA_FAILURE = "GET_GROCERIES_DATA_FAILURE";